services:
  react-app:
    image: react-app
    container_name: react-app
    restart: unless-stopped
    ports:
      - "80"
    networks:
      - npm_shared_net

networks:
  npm_shared_net:
    name: npm-network
    external: true
